export const SAMPLE = 'SAMPLE';

// navigation
export const TRY_TO_DOWNLOAD_NAVIGATION = 'TRY_TO_DOWNLOAD_NAVIGATION';
export const ERROR_DOWNLOADING_NAVIGATION = 'ERROR_DOWNLOADING_NAVIGATION';
export const NAVIGATION_SUCCESSFULLY_DOWNLOADED =
  'NAVIGATION_SUCCESSFULLY_DOWNLOADED';
