// navigation
export const TRY_TO_DOWNLOAD_NAVIGATION = 'TRY_TO_DOWNLOAD_NAVIGATION';
export const ERROR_DOWNLOADING_NAVIGATION = 'ERROR_DOWNLOADING_NAVIGATION';
export const NAVIGATION_SUCCESSFULLY_DOWNLOADED =
  'NAVIGATION_SUCCESSFULLY_DOWNLOADED';

// testimonials
export const TRY_TO_DOWNLOAD_TESTIMONIALS = 'TRY_TO_DOWNLOAD_TESTIMONIALS';
export const ERROR_DOWNLOADING_TESTIMONIALS = 'ERROR_DOWNLOADING_TESTIMONIALS';
export const SUCCESSFUL_TESTIMONIAL_DOWNLOAD =
  'SUCCESSFUL_TESTIMONIAL_DOWNLOAD';
export const CHANGE_TESTIMONIAL = 'CHANGE_TESTIMONIAL';

// configurator
export const TRY_TO_DOWNLOAD_CONFIGURATOR = 'TRY_TO_DOWNLOAD_CONFIGURATOR';
export const ERROR_DOWNLOADING_CONFIGURATOR = 'ERROR_DOWNLOADING_CONFIGURATOR';
export const SUCCESSFUL_CONFIGURATOR_DOWNLOAD =
  'SUCCESSFUL_CONFIGURATOR_DOWNLOAD';

export const UPDATE_MONTHLY_EXPENSE = 'UPDATE_MONTHLY_EXPENSE';
export const UPDATE_NUMBER_OF_EMPLOYEES = 'UPDATE_NUMBER_OF_EMPLOYEES';
